require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ValuablesController do

  # This should return the minimal set of attributes required to create a valid
  # Valuable. As you add validations to Valuable, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ValuablesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all valuables as @valuables" do
      valuable = Valuable.create! valid_attributes
      get :index, {}, valid_session
      assigns(:valuables).should eq([valuable])
    end
  end

  describe "GET show" do
    it "assigns the requested valuable as @valuable" do
      valuable = Valuable.create! valid_attributes
      get :show, {:id => valuable.to_param}, valid_session
      assigns(:valuable).should eq(valuable)
    end
  end

  describe "GET new" do
    it "assigns a new valuable as @valuable" do
      get :new, {}, valid_session
      assigns(:valuable).should be_a_new(Valuable)
    end
  end

  describe "GET edit" do
    it "assigns the requested valuable as @valuable" do
      valuable = Valuable.create! valid_attributes
      get :edit, {:id => valuable.to_param}, valid_session
      assigns(:valuable).should eq(valuable)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Valuable" do
        expect {
          post :create, {:valuable => valid_attributes}, valid_session
        }.to change(Valuable, :count).by(1)
      end

      it "assigns a newly created valuable as @valuable" do
        post :create, {:valuable => valid_attributes}, valid_session
        assigns(:valuable).should be_a(Valuable)
        assigns(:valuable).should be_persisted
      end

      it "redirects to the created valuable" do
        post :create, {:valuable => valid_attributes}, valid_session
        response.should redirect_to(Valuable.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved valuable as @valuable" do
        # Trigger the behavior that occurs when invalid params are submitted
        Valuable.any_instance.stub(:save).and_return(false)
        post :create, {:valuable => {  }}, valid_session
        assigns(:valuable).should be_a_new(Valuable)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Valuable.any_instance.stub(:save).and_return(false)
        post :create, {:valuable => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested valuable" do
        valuable = Valuable.create! valid_attributes
        # Assuming there are no other valuables in the database, this
        # specifies that the Valuable created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Valuable.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => valuable.to_param, :valuable => { "these" => "params" }}, valid_session
      end

      it "assigns the requested valuable as @valuable" do
        valuable = Valuable.create! valid_attributes
        put :update, {:id => valuable.to_param, :valuable => valid_attributes}, valid_session
        assigns(:valuable).should eq(valuable)
      end

      it "redirects to the valuable" do
        valuable = Valuable.create! valid_attributes
        put :update, {:id => valuable.to_param, :valuable => valid_attributes}, valid_session
        response.should redirect_to(valuable)
      end
    end

    describe "with invalid params" do
      it "assigns the valuable as @valuable" do
        valuable = Valuable.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Valuable.any_instance.stub(:save).and_return(false)
        put :update, {:id => valuable.to_param, :valuable => {  }}, valid_session
        assigns(:valuable).should eq(valuable)
      end

      it "re-renders the 'edit' template" do
        valuable = Valuable.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Valuable.any_instance.stub(:save).and_return(false)
        put :update, {:id => valuable.to_param, :valuable => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested valuable" do
      valuable = Valuable.create! valid_attributes
      expect {
        delete :destroy, {:id => valuable.to_param}, valid_session
      }.to change(Valuable, :count).by(-1)
    end

    it "redirects to the valuables list" do
      valuable = Valuable.create! valid_attributes
      delete :destroy, {:id => valuable.to_param}, valid_session
      response.should redirect_to(valuables_url)
    end
  end

end
